- name: Check ansible version
  delegate_to: localhost
  run_once: true
  vars:
    min_version: "2.16.0"
    max_version: "2.21.0"
  fail:
    msg: "WARNING: Ansible version is {{ ansible_version.full }} and should be >= {{ min_version }} and < {{ max_version }}"
  when: ansible_version.full < min_version or ansible_version.full >= max_version
  ignore_errors: True

- name: d
  debug:
    var: conf_dir

- name: Setup configuration directory
  set_fact:
    conf_dir: "{{ conf_dir | default(playbook_dir ~ '/conf') }}"
    h: "{{ h | default('all') }}"
