- name: Basic checks
  include_tasks: root.yml

- name: Detect os
  include_tasks: os-detect.yml

- name: Configure timezone
  include_tasks: tz.yml
  args:
    apply:
      become: yes

- name: sendmail
  include_tasks: sendmail.yml
  args:
    apply:
      become: yes
  when: ub24_04 or ub22_04

- name: configure base os
  include_tasks: os-ubuntu-base.yml
  args:
    apply:
      become: yes
  when: ub24_04 or ub22_04

- name: configure hosts
  include_tasks: hosts.yml
  args:
    apply:
      become: yes

- name: configure admins
  args:
    apply:
      become: yes
  include_tasks: admins.yml
  when: ub24_04 or ub22_04

- name: configure sw
  include_tasks: os-ubuntu-sw.yml
  args:
    apply:
      become: yes
  when: ub24_04 or ub22_04

- name: configure logs
  include_tasks: log.yml
  args:
    apply:
      become: yes
  when: ub24_04 or ub22_04

- name: configure users
  include_tasks: users.yml
  args:
    apply:
      become: yes
  when: ub24_04 or ub22_04
