- name: Install tools missing from minimized ubuntu
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time | default(86400) }}"
    pkg:
      - etckeeper # not strictly missing, but nice to install first
      - tzdata
      - logrotate
      - rsyslog
      - uuid-runtime
      - cron
