- name: ansible_user check
  ansible.builtin.fail:
    msg: "ansible_user must be root or included in admins, ansible_user:{{ ansible_user }}, admins: {{ admin_uids | map(attribute='name') }}"
  when:
    - ansible_user != "root"
    - admin_uids | map(attribute='name') is not contains(ansible_user)

- name: Check sudo root
  become: true
  ansible.builtin.command: whoami
  changed_when: false
